roberta:
    model_weights: models/roberta
    # модель будет оставлять ответы только выше этой вероятности
    cut_off_proba: 0.
    # вопросы, на которые модель будет искать ответ
    questions:
    -   на что можно посмотреть в этом месте
    -   что понравилось в этом месте
    -   что делать в этом месте
    -   какие ожидания от этого места
    -   для кого это место
    stop_pos:
    -   PUNCT
    norm_words:
    -   не
    -   на
    -   под
    -   и
    -   для
    -   о
    -   с
    -   из
    -   по
    -   в
    -   а
    -   за
    -   до
