roberta:
    model_weights: models/roberta
    # модель будет оставлять ответы только выше этой вероятности
    cut_off_proba: 0.
    # вопросы, на которые модель будет искать ответ
    questions:
    -   что можно сказать об этом месте
    -   чем можно заняться
    -   какая стоимость в деньгах
    -   с кем прийти в это место
    stop_pos:
    -   PUNCT
    norm_words:
    -   не
    -   на
    -   под
    -   и
    -   для
    -   о
    -   с
    -   из
    -   по
    -   в
    -   а
    -   за
    -   до
