pathes:
    data:
        initial_data: "data/initial_data"
        intermediate_data: "data/intermediate_data"
        prepared_data: "data/prepared_data"
models:
    roberta:
        model_weights: "models/roberta"
        stop_pos:
        -   на
        norm_words:
        -   под
