[tool.poetry]
name = "lewart-tags-model"
version = "0.1.0"
description = "lewart_model_for_tagging"
authors = ["smeyanoff <miradg99@gmail.com>"]
readme = "README.md"
packages = []

[tool.poetry.dependencies]
python = "^3.10"
pandas = "^2.0.2"
sqlalchemy = "1.4.0"
numpy = "^1.25.0"
dvc = "^3.1.0"
dvc-gdrive = "^2.19.2"
poetry-dotenv-plugin = "^0.1.0"
pyarrow = "^12.0.1"
poethepoet = "^0.20.0"
psycopg2-binary = "^2.9.6"


[tool.poetry.group.dev.dependencies]
ipykernel = "^6.23.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
